In [2]:
import numpy as np

In [4]:
pop_mean = [13, 5]
pop_mean

[13, 5]

In [5]:
pop_cov = [[5,.3], [.3,2]]
pop_cov

[[5, 0.3], [0.3, 2]]

In [15]:
mySample = []
mySample = np.random.multivariate_normal(pop_mean, pop_cov, 100)
mySample
print(mySample.size)

200


In [11]:
mySample.T

array([[15.89255987, 13.66589349, 14.86449428, 14.27420879, 17.48087003,
        14.88384686, 14.26346277, 14.15306617, 14.74898923, 13.93852504,
        13.21288389, 13.32065784, 15.17656957, 13.13220293,  8.94983013,
        13.45647452, 12.12232475, 14.82759169, 12.07042886, 15.90946147,
        12.80322706, 10.69901903, 13.59605905,  7.66112486, 11.86969266,
        12.3898279 , 12.91137482, 15.71790489, 12.66189298, 15.44590266,
        16.53957766, 10.84617687, 16.61619001, 14.3874941 , 11.14169112,
        13.73086477, 11.21061839, 14.8226115 , 17.45180078, 18.68999879,
        15.89943019, 11.77635139, 12.13973077, 12.52157025, 16.07208313,
         6.77260401, 13.66792748, 14.42471488, 12.99147299, 10.04307462,
        16.17256782, 10.85481707, 13.11092302,  8.58380987, 15.25891914,
        12.52196966, 13.73159189, 15.26568072, 14.69950308,  8.90879951,
        10.39666759, 16.10153897, 12.40193645, 14.91522368, 13.93968787,
        14.49794204, 12.26501549, 16.05314786, 10.6

In [10]:
np.cov(mySample.T)

array([[5.06660664, 0.67883543],
       [0.67883543, 2.00164375]])

In [18]:
np.mean(mySample, axis=0)

array([12.98314097,  5.03929325])

In [19]:
def gen_bivariate_normal_sample(pop_mean, pop_cov, sample_size):
    mySample = []
    meanMatrix = []
    covMatrix = []
    mySample = np.random.multivariate_normal(pop_mean, pop_cov, sample_size)
    meanMatrix = np.mean(mySample, axis=0)
    covMatrix = np.cov(mySample.T)
    return (meanMatrix, covMatrix)

In [20]:
results = ()
results = gen_bivariate_normal_sample(pop_mean, pop_cov, 100)

In [21]:
results

(array([13.20354299,  4.93157025]), array([[5.18627055, 0.02369612],
        [0.02369612, 2.46650322]]))

In [22]:
results = ()
results = gen_bivariate_normal_sample(pop_mean, pop_cov, 1000)
results

(array([12.94841668,  5.00877208]), array([[5.19496838, 0.42653046],
        [0.42653046, 2.0776509 ]]))